services:
  perlite:
    image: sec77/perlite:latest
    build: 
      context: perlite
    container_name: perlite
    restart: unless-stopped
    environment:
      - NOTES_PATH=highres
      - HIDE_FOLDERS=docs,private,trash
      - HIDDEN_FILE_ACCESS=false
      - LINE_BREAKS=true
      - ABSOLUTE_PATHS=false
      - ALLOWED_FILE_LINK_TYPES=pdf,mp4
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=true
      - SHOW_LOCAL_GRAPH=true
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=true
      - TEMP_PATH=/tmp
      - SITE_TITLE=Highres Wiki
      - SITE_TYPE=article
      - SITE_URL=
      - SITE_IMAGE=
      - SITE_DESC=
      - SITE_NAME=Perlite
      - SITE_TWITTER=
      - SITE_LOGO=perlite.svg
      - SITE_HOMEPAGE=https://perlite.secure77.de/
      - SITE_GITHUB=https://github.com/SelfScriptKiddies/Perlite
      - GITHUB_STORAGE=https://github.com/SelfScriptKiddies/wiki-storage
    volumes:
      - ./storage:/var/www/perlite/highres:ro

  web:
    image: nginx:stable
    container_name: perlite_web
    restart: unless-stopped
    ports:
      - 3010:80
    volumes:
      - ./web/config/perlite.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from: 
      - perlite       
    depends_on:
      - perlite

